import Head from 'next/head'
import Footer from '../layout/Footer'
import Header from '../layout/Header'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Clinic</title>
        <meta name='description' content='Generated by create next app' />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className='min-h-[calc(100vh-264px)]'>
        <div className='container p-20'>
          <Component {...pageProps} />
        </div>
      </main>
      <Footer />
    </>
  )
}

export default MyApp
